import type { ProofPortfolioState } from "@/domain/types";

export const initialState: ProofPortfolioState = {
  ledger: [
    {
      id: "ledger-1",
      date: "2026-01-05",
      type: "deposit",
      amount: 2500,
      source: "Paycheck",
      notes: "Initial paper account funding",
    },
    {
      id: "ledger-2",
      date: "2026-01-19",
      type: "deposit",
      amount: 1250,
      source: "Paycheck",
      notes: "Second payroll deposit",
    },
    {
      id: "ledger-3",
      date: "2026-02-03",
      type: "stock_buy",
      amount: -1098,
      source: "BUY NVDA",
      tradeId: "trade-1",
    },
    {
      id: "ledger-4",
      date: "2026-02-21",
      type: "stock_sell",
      amount: 1187.5,
      source: "CLOSE NVDA",
      tradeId: "trade-1",
      notes: "Realized P/L $89.50",
    },
    {
      id: "ledger-5",
      date: "2026-03-02",
      type: "stock_buy",
      amount: -1358.4,
      source: "BUY AMD",
      tradeId: "trade-2",
    },
  ],
  trades: [
    {
      id: "trade-1",
      ticker: "NVDA",
      assetType: "stock",
      action: "buy",
      quantity: 10,
      entryPrice: 109.8,
      exitPrice: 118.75,
      openedAt: "2026-02-03",
      closedAt: "2026-02-21",
      thesis: "Momentum continuation after consolidation.",
      strategy: "Breakout retest",
      riskAmount: 95,
      target: 120,
      stopLoss: 100.3,
      notes: "Closed after target zone tagged.",
      status: "closed",
    },
    {
      id: "trade-2",
      ticker: "AMD",
      assetType: "stock",
      action: "buy",
      quantity: 12,
      entryPrice: 113.2,
      openedAt: "2026-03-02",
      thesis: "Relative strength against semis basket.",
      strategy: "Swing pullback",
      riskAmount: 120,
      target: 165,
      stopLoss: 103.2,
      notes: "Let winner work while above trend.",
      status: "open",
    },
  ],
  auditLog: [
    {
      id: "audit-1",
      date: "2026-02-21",
      entityType: "trade",
      entityId: "trade-1",
      action: "closed",
      summary: "Closed NVDA at $118.75. Closed trades are append-only in the MVP.",
    },
  ],
};
